import { SignatureEnvelopeType } from '@prisma/client';

export type EnvelopeFieldType =
  | 'text'
  | 'signature'
  | 'initials'
  | 'date'
  | 'address'
  | 'checkbox'
  | 'name'
  | 'email'
  | 'price'
  | 'mls';

export interface EnvelopeFieldPlacement {
  id: string;
  type: EnvelopeFieldType;
  x: number;
  y: number;
  width: number;
  height: number;
  page: number;
  value: string;
  placeholder: string;
  assignedTo?: string;
  required: boolean;
  appliesToPages?: number[];
  autoGenerated?: boolean;
}

type RawEnvelopeField = Partial<EnvelopeFieldPlacement> & {
  id?: unknown;
  type?: unknown;
  required?: unknown;
  assignedTo?: unknown;
  appliesToPages?: unknown;
};

type SignerLike = {
  role?: string | null;
};

const FIELD_TYPES = new Set<EnvelopeFieldType>([
  'text',
  'signature',
  'initials',
  'date',
  'address',
  'checkbox',
  'name',
  'email',
  'price',
  'mls',
]);

const REPC_PAGE_COUNT = 6;

const normalizeRole = (value: unknown): string | undefined => {
  if (typeof value !== 'string') return undefined;
  const normalized = value.trim().toUpperCase();
  return normalized || undefined;
};

const inferRoleFromField = (field: RawEnvelopeField): string | undefined => {
  const haystack = [field.id, field.placeholder]
    .filter((value): value is string => typeof value === 'string' && value.trim().length > 0)
    .join(' ')
    .toLowerCase();

  if (!haystack) return undefined;
  if (haystack.includes('buyer')) return 'BUYER';
  if (haystack.includes('seller')) return 'SELLER';
  if (haystack.includes('agent')) return 'AGENT';
  return undefined;
};

const normalizeFieldType = (value: unknown): EnvelopeFieldType | null => {
  if (typeof value !== 'string') return null;
  const normalized = value.trim().toLowerCase() as EnvelopeFieldType;
  return FIELD_TYPES.has(normalized) ? normalized : null;
};

const numberOrDefault = (value: unknown, fallback: number) => {
  const parsed = typeof value === 'number' ? value : Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
};

const normalizePages = (value: unknown): number[] | undefined => {
  if (!Array.isArray(value)) return undefined;

  const pages = value
    .map((entry) => Number(entry))
    .filter((entry) => Number.isInteger(entry) && entry > 0);

  if (pages.length === 0) return undefined;
  return Array.from(new Set(pages)).sort((left, right) => left - right);
};

const roleLabel = (role?: string) => {
  switch (role) {
    case 'BUYER':
      return 'Buyer';
    case 'SELLER':
      return 'Seller';
    case 'AGENT':
      return 'Agent';
    default:
      return 'Signer';
  }
};

const uniqueSignerRoles = (signers: SignerLike[]) => {
  const roles = signers
    .map((signer) => normalizeRole(signer.role))
    .filter((role): role is string => Boolean(role));

  return Array.from(new Set(roles));
};

const buildDefaultRepcFields = (signers: SignerLike[]): EnvelopeFieldPlacement[] => {
  const roles = uniqueSignerRoles(signers);
  const scopedRoles = roles.filter((role) => role === 'BUYER' || role === 'SELLER');
  const fallbackRoles = scopedRoles.length > 0 ? scopedRoles : roles;

  return fallbackRoles.flatMap((role) => {
    const label = roleLabel(role);
    return [
      {
        id: `auto-${role.toLowerCase()}-initials`,
        type: 'initials',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        page: 1,
        value: '',
        placeholder: `${label} initials for every required tab`,
        assignedTo: role,
        required: true,
        appliesToPages: Array.from({ length: REPC_PAGE_COUNT }, (_, index) => index + 1),
        autoGenerated: true,
      },
      {
        id: `auto-${role.toLowerCase()}-signature`,
        type: 'signature',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        page: REPC_PAGE_COUNT,
        value: '',
        placeholder: `${label} final signature`,
        assignedTo: role,
        required: true,
        appliesToPages: [REPC_PAGE_COUNT],
        autoGenerated: true,
      },
    ];
  });
};

const buildGenericFields = (signers: SignerLike[]): EnvelopeFieldPlacement[] => {
  const roles = uniqueSignerRoles(signers);

  return roles.map((role) => ({
    id: `auto-${role.toLowerCase()}-signature`,
    type: 'signature',
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    page: 1,
    value: '',
    placeholder: `${roleLabel(role)} signature`,
    assignedTo: role,
    required: true,
    appliesToPages: [1],
    autoGenerated: true,
  }));
};

export const normalizeEnvelopeFields = (fields: unknown): EnvelopeFieldPlacement[] => {
  if (!Array.isArray(fields)) return [];

  return fields
    .map((field): EnvelopeFieldPlacement | null => {
      const raw = field as RawEnvelopeField;
      if (typeof raw.id !== 'string' || !raw.id.trim()) return null;

      const type = normalizeFieldType(raw.type);
      if (!type) return null;

      return {
        id: raw.id.trim(),
        type,
        x: numberOrDefault(raw.x, 0),
        y: numberOrDefault(raw.y, 0),
        width: numberOrDefault(raw.width, 0),
        height: numberOrDefault(raw.height, 0),
        page: Math.max(1, Math.trunc(numberOrDefault(raw.page, 1))),
        value: typeof raw.value === 'string' ? raw.value : '',
        placeholder: typeof raw.placeholder === 'string' ? raw.placeholder : '',
        assignedTo: normalizeRole(raw.assignedTo) || inferRoleFromField(raw),
        required: raw.required !== false,
        appliesToPages: normalizePages(raw.appliesToPages),
        autoGenerated: raw.autoGenerated === true,
      };
    })
    .filter((field): field is EnvelopeFieldPlacement => Boolean(field));
};

export const buildDefaultEnvelopeFields = (
  envelopeType: SignatureEnvelopeType | string,
  signers: SignerLike[],
): EnvelopeFieldPlacement[] => {
  const normalizedType = String(envelopeType || '').toUpperCase();
  if (normalizedType === 'REPC') {
    return buildDefaultRepcFields(signers);
  }
  return buildGenericFields(signers);
};

export const resolveEnvelopeFields = ({
  envelopeType,
  signers,
  fields,
}: {
  envelopeType: SignatureEnvelopeType | string;
  signers: SignerLike[];
  fields: unknown;
}): EnvelopeFieldPlacement[] => {
  const explicitFields = normalizeEnvelopeFields(fields);
  if (explicitFields.length > 0) {
    return explicitFields;
  }
  return buildDefaultEnvelopeFields(envelopeType, signers);
};

export const resolveSnapshotWithEnvelopeFields = ({
  envelopeType,
  signers,
  snapshot,
}: {
  envelopeType: SignatureEnvelopeType | string;
  signers: SignerLike[];
  snapshot: Record<string, unknown> | null | undefined;
}): Record<string, unknown> => {
  const safeSnapshot = snapshot && typeof snapshot === 'object' ? snapshot : {};
  return {
    ...safeSnapshot,
    __esignFieldPlacements: resolveEnvelopeFields({
      envelopeType,
      signers,
      fields: (safeSnapshot as Record<string, unknown>).__esignFieldPlacements,
    }),
  };
};

export const isFieldAssignedToSigner = ({
  field,
  signerRole,
  signerCount,
}: {
  field: Pick<EnvelopeFieldPlacement, 'assignedTo'>;
  signerRole: string;
  signerCount: number;
}): boolean => {
  const normalizedRole = normalizeRole(signerRole);
  if (!normalizedRole) return false;
  if (field.assignedTo) {
    return normalizeRole(field.assignedTo) === normalizedRole;
  }
  return signerCount <= 1;
};