-- Add missing Listing fields to match the Prisma schema

DO $$ BEGIN
  ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'PENDING';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "Listing"
  ADD COLUMN IF NOT EXISTS "addressLine1" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "city" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "state" TEXT NOT NULL DEFAULT 'UT',
  ADD COLUMN IF NOT EXISTS "zipCode" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "beds" INTEGER,
  ADD COLUMN IF NOT EXISTS "baths" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "sqft" INTEGER,
  ADD COLUMN IF NOT EXISTS "heroImageUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "isFeatured" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "totalBlasts" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "totalClicks" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "goLiveDate" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "nextOpenHouseAt" TIMESTAMP(3);
