import { useEffect, useRef, useState } from 'react';
import * as pdfjsLib from 'pdfjs-dist';
import pdfjsWorker from 'pdfjs-dist/build/pdf.worker.min?url';

pdfjsLib.GlobalWorkerOptions.workerSrc = pdfjsWorker;

const SAFE_PDFJS_OPTIONS = {
  enableScripting: false,
  isEvalSupported: false,
  stopAtErrors: true,
} as const;

type PacketField = {
  id: string;
  type: 'text' | 'signature' | 'initials' | 'date' | 'address' | 'checkbox' | 'name' | 'email' | 'price' | 'mls';
  page?: number;
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  placeholder?: string;
  appliesToPages?: number[];
  autoGenerated?: boolean;
};

type RenderedPage = {
  pageNumber: number;
  imageSrc: string;
  renderedWidth: number;
  renderedHeight: number;
  baseWidth: number;
  baseHeight: number;
};

type Hotspot = {
  key: string;
  fieldId: string;
  pageNumber: number;
  left: number;
  top: number;
  width: number;
  height: number;
  label: string;
  hint: string;
};

const REPC_BUYER_INITIAL = { left: 187.52, top: 707.92, width: 36, height: 11 };
const REPC_SELLER_INITIAL = { left: 420.68, top: 707.92, width: 36, height: 11 };
const REPC_SIGNATURES: Record<string, { left: number; top: number; width: number; height: number }> = {
  BUYER: { left: 31.94, top: 387.17, width: 172.8, height: 18.7 },
  SELLER: { left: 309.47, top: 386.13, width: 225.9, height: 18.7 },
};

const clamp = (value: number, min: number, max: number) => Math.min(Math.max(value, min), max);

const getHotspotLabel = (fieldType: PacketField['type']) => {
  if (fieldType === 'initials') return 'Initial here';
  if (fieldType === 'signature') return 'Sign here';
  if (fieldType === 'checkbox') return 'Acknowledge';
  return 'Complete here';
};

const getHotspotHint = (fieldType: PacketField['type']) => {
  if (fieldType === 'initials') return 'Click to adopt initials';
  if (fieldType === 'signature') return 'Click to adopt signature';
  if (fieldType === 'checkbox') return 'Click to jump to acknowledgement';
  return 'Click to jump to this field';
};

const getGenericAutoRect = (field: PacketField) => {
  if (field.type === 'signature') {
    return { left: 52, top: 646, width: 220, height: 28 };
  }
  if (field.type === 'initials') {
    return { left: 470, top: 58, width: 52, height: 24 };
  }
  return { left: 64, top: 96, width: 180, height: 28 };
};

const resolveRepcAutoRect = ({
  field,
  pageNumber,
  signerRole,
}: {
  field: PacketField;
  pageNumber: number;
  signerRole: string;
}) => {
  if (field.type === 'initials') {
    return signerRole === 'SELLER' ? REPC_SELLER_INITIAL : REPC_BUYER_INITIAL;
  }

  if (field.type === 'signature') {
    return REPC_SIGNATURES[signerRole] || REPC_SIGNATURES.BUYER;
  }

  if (field.type === 'date' && pageNumber === 6) {
    if (signerRole === 'SELLER') {
      return { left: 542, top: 385, width: 48, height: 18 };
    }
    return { left: 209, top: 385, width: 56, height: 18 };
  }

  return null;
};

const getFieldPages = (field: PacketField) => {
  if (Array.isArray(field.appliesToPages) && field.appliesToPages.length > 0) {
    return field.appliesToPages;
  }
  if (typeof field.page === 'number' && field.page > 0) {
    return [field.page];
  }
  return [1];
};

const resolveHotspotRect = ({
  field,
  page,
  envelopeType,
  signerRole,
}: {
  field: PacketField;
  page: RenderedPage;
  envelopeType?: string;
  signerRole: string;
}) => {
  const isRepc = String(envelopeType || '').toUpperCase() === 'REPC';
  let baseRect: { left: number; top: number; width: number; height: number } | null = null;

  if (
    !field.autoGenerated &&
    Number.isFinite(field.x) &&
    Number.isFinite(field.y) &&
    Number.isFinite(field.width) &&
    Number.isFinite(field.height)
  ) {
    baseRect = {
      left: Number(field.x),
      top: Number(field.y),
      width: Math.max(Number(field.width), 22),
      height: Math.max(Number(field.height), 18),
    };
  } else if (field.autoGenerated && isRepc) {
    baseRect = resolveRepcAutoRect({ field, pageNumber: page.pageNumber, signerRole });
  } else {
    baseRect = getGenericAutoRect(field);
  }

  if (!baseRect) return null;

  const left = (baseRect.left / page.baseWidth) * page.renderedWidth;
  const top = (baseRect.top / page.baseHeight) * page.renderedHeight;
  const width = (baseRect.width / page.baseWidth) * page.renderedWidth;
  const height = (baseRect.height / page.baseHeight) * page.renderedHeight;

  return {
    left: clamp(left, 0, Math.max(0, page.renderedWidth - width)),
    top: clamp(top, 0, Math.max(0, page.renderedHeight - height)),
    width: Math.max(width, 24),
    height: Math.max(height, 18),
  };
};

export function InteractivePacketViewer({
  pdfUrl,
  envelopeType,
  signerRole,
  fields,
  activeFieldId,
  activeHotspotKey,
  missingFieldIds,
  missingHotspotKeys,
  completedFieldIds,
  completedHotspotKeys,
  disabled,
  onActivateField,
  onReadyChange,
}: {
  pdfUrl: string | null;
  envelopeType?: string;
  signerRole: string;
  fields: PacketField[];
  activeFieldId: string | null;
  activeHotspotKey?: string | null;
  missingFieldIds: string[];
  missingHotspotKeys?: string[];
  completedFieldIds: string[];
  completedHotspotKeys?: string[];
  disabled?: boolean;
  onActivateField: (fieldId: string, hotspotKey?: string, pageNumber?: number) => void;
  onReadyChange?: (ready: boolean) => void;
}) {
  const containerRef = useRef<HTMLDivElement>(null);
  const hotspotRefs = useRef<Record<string, HTMLButtonElement | null>>({});
  const [pages, setPages] = useState<RenderedPage[]>([]);
  const [containerWidth, setContainerWidth] = useState(0);
  const [loading, setLoading] = useState(false);
  const [renderError, setRenderError] = useState<string | null>(null);

  useEffect(() => {
    const element = containerRef.current;
    if (!element) return;

    const updateWidth = () => {
      setContainerWidth(Math.max(320, Math.floor(element.clientWidth - 24)));
    };

    updateWidth();
    const observer = new ResizeObserver(updateWidth);
    observer.observe(element);

    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    let cancelled = false;

    const renderPdf = async () => {
      if (!pdfUrl || !containerWidth) {
        setPages([]);
        setRenderError(null);
        setLoading(false);
        onReadyChange?.(false);
        return;
      }

      setLoading(true);
      setRenderError(null);
      onReadyChange?.(false);

      try {
        const absolutePdfUrl = new URL(pdfUrl, window.location.origin).toString();
        const loadingTask = pdfjsLib.getDocument({ url: absolutePdfUrl, ...SAFE_PDFJS_OPTIONS });
        const pdfDocument = await loadingTask.promise;
        const nextPages: RenderedPage[] = [];
        const targetWidth = Math.min(1040, containerWidth);

        for (let pageNumber = 1; pageNumber <= pdfDocument.numPages; pageNumber += 1) {
          const page = await pdfDocument.getPage(pageNumber);
          const baseViewport = page.getViewport({ scale: 1 });
          const scale = targetWidth / baseViewport.width;
          const viewport = page.getViewport({ scale });
          const canvas = document.createElement('canvas');
          const context = canvas.getContext('2d', { alpha: false });

          if (!context) {
            continue;
          }

          canvas.width = Math.floor(viewport.width);
          canvas.height = Math.floor(viewport.height);

          await page.render({ canvasContext: context, viewport, canvas }).promise;

          nextPages.push({
            pageNumber,
            imageSrc: canvas.toDataURL('image/jpeg', 0.92),
            renderedWidth: viewport.width,
            renderedHeight: viewport.height,
            baseWidth: baseViewport.width,
            baseHeight: baseViewport.height,
          });
        }

        if (cancelled) return;

        setPages(nextPages);
        setLoading(false);
        onReadyChange?.(true);
      } catch (error) {
        console.error('Failed to render interactive signer PDF:', error);
        if (cancelled) return;
        setPages([]);
        setLoading(false);
        setRenderError('Interactive preview unavailable for this packet. Use the open/download links below.');
        onReadyChange?.(true);
      }
    };

    renderPdf();

    return () => {
      cancelled = true;
    };
  }, [pdfUrl, containerWidth, onReadyChange]);

  const hotspots: Hotspot[] = [];
  const completedSet = new Set(completedFieldIds);
  const missingSet = new Set(missingFieldIds);
  const completedHotspotSet = new Set(completedHotspotKeys || []);
  const missingHotspotSet = new Set(missingHotspotKeys || []);
  const pendingCount = missingHotspotKeys?.length ?? missingFieldIds.length;
  const completedCount = completedHotspotKeys?.length ?? completedFieldIds.length;

  fields.forEach((field, index) => {
    const pageNumbers = getFieldPages(field);
    pageNumbers.forEach((pageNumber, hotspotIndex) => {
      const page = pages.find((entry) => entry.pageNumber === pageNumber);
      if (!page) return;
      const rect = resolveHotspotRect({ field, page, envelopeType, signerRole });
      if (!rect) return;

      hotspots.push({
        key: `${field.id}-${pageNumber}-${hotspotIndex}`,
        fieldId: field.id,
        pageNumber,
        left: rect.left,
        top: rect.top,
        width: rect.width,
        height: rect.height,
        label: `${index + 1}`,
        hint: getHotspotHint(field.type),
      });
    });
  });

  useEffect(() => {
    if (!activeFieldId && !activeHotspotKey) return;
    const activeHotspot = activeHotspotKey
      ? hotspots.find((entry) => entry.key === activeHotspotKey)
      : hotspots.find((entry) => entry.fieldId === activeFieldId);
    if (!activeHotspot) return;
    hotspotRefs.current[activeHotspot.key]?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  }, [activeFieldId, activeHotspotKey, hotspots]);

  return (
    <div ref={containerRef} className="relative h-full min-h-[620px] overflow-y-auto bg-slate-950/20">
      {(loading || !pdfUrl) && !renderError && (
        <div className="absolute inset-0 z-10 flex items-center justify-center bg-slate-900/35 text-sm text-slate-200">
          Loading interactive contract preview…
        </div>
      )}

      {!renderError && pdfUrl && (
        <div className="sticky top-0 z-[5] border-b border-white/10 bg-slate-950/85 px-4 py-3 backdrop-blur-xl">
          <div className="flex flex-wrap items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-300">
            <span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-slate-200">
              Tap numbered packet tabs
            </span>
            <span className="rounded-full border border-cyan-400/25 bg-cyan-500/10 px-3 py-1 text-cyan-100">
              {pendingCount} needing you
            </span>
            <span className="rounded-full border border-amber-400/25 bg-amber-500/10 px-3 py-1 text-amber-100">
              Amber = active
            </span>
            <span className="rounded-full border border-emerald-400/25 bg-emerald-500/10 px-3 py-1 text-emerald-100">
              {completedCount} ready
            </span>
          </div>
        </div>
      )}

      {renderError && (
        <div className="flex min-h-[620px] items-center justify-center px-6 text-center text-sm text-slate-300">
          {renderError}
        </div>
      )}

      {!renderError && pages.length > 0 && (
        <div className="space-y-6 p-3 md:p-4">
          {pages.map((page) => {
            const pageHotspots = hotspots.filter((entry) => entry.pageNumber === page.pageNumber);

            return (
              <div key={page.pageNumber} className="mx-auto w-full max-w-[1040px] space-y-2.5">
                <div className="flex items-center justify-between px-1 text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-400">
                  <span>Page {page.pageNumber}</span>
                  <span>{pageHotspots.length > 0 ? `${pageHotspots.length} active tab${pageHotspots.length > 1 ? 's' : ''}` : 'No active tabs on this page'}</span>
                </div>
                <div
                  className="relative overflow-hidden rounded-[22px] border border-white/10 bg-white shadow-[0_28px_80px_rgba(15,23,42,0.42)]"
                  style={{ width: page.renderedWidth, minHeight: page.renderedHeight }}
                >
                  <img
                    src={page.imageSrc}
                    alt={`Contract page ${page.pageNumber}`}
                    className="block h-auto w-full select-none"
                    draggable={false}
                  />

                  {pageHotspots.map((hotspot) => {
                    const isCompleted = completedHotspotSet.size > 0
                      ? completedHotspotSet.has(hotspot.key)
                      : completedSet.has(hotspot.fieldId);
                    const isMissing = missingHotspotSet.size > 0
                      ? missingHotspotSet.has(hotspot.key)
                      : missingSet.has(hotspot.fieldId);
                    const isActive = activeHotspotKey ? hotspot.key === activeHotspotKey : hotspot.fieldId === activeFieldId;
                    const hotspotLabel = getHotspotLabel(fields.find((field) => field.id === hotspot.fieldId)?.type || 'text');

                    return (
                      <button
                        key={hotspot.key}
                        ref={(element) => {
                          hotspotRefs.current[hotspot.key] = element;
                        }}
                        type="button"
                        disabled={disabled}
                        onClick={() => onActivateField(hotspot.fieldId, hotspot.key, hotspot.pageNumber)}
                        className={`absolute rounded-xl border-2 transition-all ${
                          isActive
                            ? 'border-amber-300 bg-amber-300/18 shadow-[0_0_0_4px_rgba(251,191,36,0.18),0_18px_30px_rgba(15,23,42,0.28)]'
                            : isCompleted
                              ? 'border-emerald-300/90 bg-emerald-300/16 shadow-[0_10px_18px_rgba(16,185,129,0.18)]'
                              : isMissing
                                ? 'border-cyan-300/95 bg-cyan-300/16 shadow-[0_0_0_3px_rgba(34,211,238,0.14),0_16px_28px_rgba(14,165,233,0.16)]'
                                : 'border-slate-200/80 bg-slate-100/12 shadow-[0_12px_24px_rgba(15,23,42,0.18)]'
                        } ${isActive ? 'animate-pulse' : ''} ${disabled ? 'cursor-not-allowed opacity-70' : 'cursor-pointer hover:scale-[1.01] hover:bg-cyan-300/18'}`}
                        style={{
                          left: hotspot.left,
                          top: hotspot.top,
                          width: hotspot.width,
                          height: hotspot.height,
                        }}
                        aria-label={hotspot.hint}
                        title={hotspot.hint}
                      >
                        <span className="absolute -left-2 -top-2 inline-flex h-7 min-w-7 items-center justify-center rounded-full border border-slate-950/70 bg-slate-950 text-[11px] font-bold text-white px-1 shadow-lg shadow-slate-950/60">
                          {hotspot.label}
                        </span>
                        <span
                          className={`absolute left-1/2 -translate-x-1/2 whitespace-nowrap rounded-full border border-slate-900/80 bg-slate-950/90 px-2.5 py-1 text-[10px] font-semibold text-white shadow-lg ${
                            isActive || isMissing ? '-top-8 inline-flex' : 'bottom-2 hidden md:inline-flex'
                          }`}
                        >
                          {hotspotLabel}
                        </span>
                      </button>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}