import { useEffect, useRef, useState } from 'react';
import { useParams } from 'react-router-dom';
import api from '../../lib/api';
import { Card } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { InteractivePacketViewer } from './InteractivePacketViewer';
import {
  StunningModal,
  ModalCancelButton,
  ModalPrimaryButton,
  ModalInput,
} from '../../components/ui/StunningModal';

interface EnvelopeView {
  contractSnapshot: any;
  envelopeType?: string;
  packetTitle?: string;
  signer?: {
    id?: string;
    name?: string;
    email?: string;
    role?: string;
  };
  signers?: Array<{
    id?: string;
    name?: string;
    role?: string;
    signedAt?: string | null;
  }>;
}

interface EnvelopeField {
  id: string;
  type: 'text' | 'signature' | 'initials' | 'date' | 'address' | 'checkbox' | 'name' | 'email' | 'price' | 'mls';
  required?: boolean;
  assignedTo?: string;
  page?: number;
  value?: string;
  placeholder?: string;
  appliesToPages?: number[];
  autoGenerated?: boolean;
}

interface RequiredTabStep {
  key: string;
  fieldId: string;
  field: EnvelopeField;
  pageNumber: number;
  stepIndex: number;
}

export function PublicSignPage() {
  const { envelopeId, signerId, token } = useParams();
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState<EnvelopeView | null>(null);
  const [name, setName] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [hash, setHash] = useState<string | null>(null);
  const [signedAt, setSignedAt] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [formError, setFormError] = useState<string | null>(null);
  const [pdfReady, setPdfReady] = useState(false);
  const [showAdoptModal, setShowAdoptModal] = useState(false);
  const [adoptModalMode, setAdoptModalMode] = useState<'finalize' | 'signature' | 'initials'>('finalize');
  const [showDisclosurePrompt, setShowDisclosurePrompt] = useState(true);
  const [initials, setInitials] = useState('');
  const [signatureStyle, setSignatureStyle] = useState<'script' | 'classic' | 'clean'>('script');
  const [focusPdf, setFocusPdf] = useState(false);
  const [showPdfFullscreen, setShowPdfFullscreen] = useState(false);
  const [fieldValues, setFieldValues] = useState<Record<string, string | boolean>>({});
  const [rulesAcknowledged, setRulesAcknowledged] = useState(false);
  const [activeRequiredFieldId, setActiveRequiredFieldId] = useState<string | null>(null);
  const [activeRequiredTabKey, setActiveRequiredTabKey] = useState<string | null>(null);
  const [reviewedTabKeys, setReviewedTabKeys] = useState<Record<string, boolean>>({});
  const [isCompactMobile, setIsCompactMobile] = useState(false);
  const nameInputRef = useRef<HTMLInputElement>(null);
  const fieldInputRefs = useRef<Record<string, HTMLInputElement | null>>({});
  const packetPdfPath = envelopeId && signerId && token
    ? `/api/esign-public/envelopes/${envelopeId}/${signerId}/${token}/pdf`
    : null;
  const packetPdfDownloadPath = envelopeId && signerId && token
    ? `/api/esign-public/envelopes/${envelopeId}/${signerId}/${token}/pdf?download=1`
    : null;

  const contractSnapshot = data?.contractSnapshot || {};
  const propertyAddress = [
    contractSnapshot.street,
    contractSnapshot.city,
    contractSnapshot.state,
    contractSnapshot.zip,
  ]
    .filter(Boolean)
    .join(', ');

  const formatMoney = (value: unknown) => {
    if (value === undefined || value === null || value === '') return null;
    const numeric = typeof value === 'string' ? Number(value) : Number(value);
    if (Number.isNaN(numeric)) return String(value);
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      maximumFractionDigits: 0,
    }).format(numeric);
  };

  const deriveInitials = (fullName: string) => {
    const cleaned = fullName.trim();
    if (!cleaned) return '';
    const parts = cleaned.split(/\s+/).filter(Boolean);
    if (parts.length === 1) {
      return parts[0].slice(0, 2).toUpperCase();
    }
    const first = parts[0]?.[0] || '';
    const last = parts[parts.length - 1]?.[0] || '';
    return `${first}${last}`.toUpperCase().slice(0, 4);
  };

  const getRoleLabel = (role?: string) => {
    switch (role) {
      case 'BUYER':
        return 'Buyer';
      case 'SELLER':
        return 'Seller';
      case 'AGENT':
        return 'Agent';
      default:
        return role || 'Participant';
    }
  };

  const formatPages = (pages?: number[]) => {
    if (!pages || pages.length === 0) return '';
    if (pages.length === 1) return `page ${pages[0]}`;
    if (pages.length === 2) return `pages ${pages[0]} and ${pages[1]}`;
    return `pages ${pages.slice(0, -1).join(', ')}, and ${pages[pages.length - 1]}`;
  };

  const getFieldLabel = (field: EnvelopeField, index: number) => {
    const explicit = field.placeholder?.trim();
    if (explicit) return explicit;

    const fallbackByType: Record<EnvelopeField['type'], string> = {
      text: 'Text',
      signature: 'Signature',
      initials: 'Initials',
      date: 'Date',
      address: 'Address',
      checkbox: 'Acknowledgement',
      name: 'Full Name',
      email: 'Email',
      price: 'Price',
      mls: 'MLS',
    };

    return `${fallbackByType[field.type]} ${index + 1}`;
  };

  const getFieldAssistText = (field: EnvelopeField) => {
    const pages = field.appliesToPages?.length ? field.appliesToPages : field.page ? [field.page] : undefined;
    const pagesLabel = formatPages(pages);

    if (field.type === 'initials' && pagesLabel) {
      return `Applies your initials automatically to ${pagesLabel}.`;
    }
    if (field.type === 'signature' && pagesLabel) {
      return `Places your adopted signature on ${pagesLabel}.`;
    }
    if (field.type === 'date' && pagesLabel) {
      return `Records the signing date for ${pagesLabel}.`;
    }
    if (pagesLabel) {
      return `Appears on ${pagesLabel}.`;
    }
    if (field.autoGenerated) {
      return 'Generated automatically from the packet role plan.';
    }
    return null;
  };

  const getFieldPagesForReview = (field: EnvelopeField) => {
    const sourcePages = field.appliesToPages?.length ? field.appliesToPages : field.page ? [field.page] : [1];
    const pages = sourcePages
      .map((page) => Math.trunc(Number(page)))
      .filter((page) => Number.isFinite(page) && page > 0);
    const uniquePages = Array.from(new Set(pages.length > 0 ? pages : [1]));
    return uniquePages.sort((left, right) => left - right);
  };

  const allFields: EnvelopeField[] = Array.isArray(contractSnapshot?.__esignFieldPlacements)
    ? contractSnapshot.__esignFieldPlacements
    : [];

  const signerRole = data?.signer?.role || '';
  const signerRoleLabel = getRoleLabel(signerRole);
  const participantCount = data?.signers?.length ?? 1;
  const signerEmail =
    data?.signer?.email ||
    (signerRole === 'BUYER'
      ? contractSnapshot.buyerEmail
      : signerRole === 'SELLER'
        ? contractSnapshot.sellerEmail
        : contractSnapshot.buyerEmail || contractSnapshot.sellerEmail || '');
  const assignedFields = allFields.filter((field) => {
    if (!field?.id || !field?.type) return false;
    if (!field.assignedTo) return participantCount <= 1;
    return field.assignedTo === signerRole;
  });
  const autoGeneratedPlan = allFields.some((field) => field.autoGenerated);
  const hasExtendedAssignedFields = assignedFields.some((field) => !['signature', 'initials'].includes(field.type));
  const hasSuggestedDefaults = assignedFields.some((field) =>
    ['initials', 'name', 'email', 'address', 'date', 'price', 'mls'].includes(field.type),
  );
  const autofillActionLabel = assignedFields.every((field) => ['signature', 'initials', 'name'].includes(field.type))
    ? 'Use My Name & Initials'
    : 'Fill My Details';
  const autofillFieldSignature = assignedFields.map((field) => `${field.id}:${field.type}`).join('|');
  const otherPendingRoles = Array.from(
    new Set(
      (data?.signers || [])
        .filter((participant) => participant.role && participant.role !== signerRole && !participant.signedAt)
        .map((participant) => participant.role as string),
    ),
  );

  const requiredAssignedFields = assignedFields.filter((field) => field.required !== false);
  const requiredTabSteps: RequiredTabStep[] = requiredAssignedFields.flatMap((field) =>
    getFieldPagesForReview(field).map((pageNumber, stepIndex) => ({
      key: `${field.id}-${pageNumber}-${stepIndex}`,
      fieldId: field.id,
      field,
      pageNumber,
      stepIndex,
    })),
  );

  const isFieldValueCompleted = (field: EnvelopeField) => {
    if (field.type === 'signature') return !!name.trim();
    if (field.type === 'initials') {
      const current = fieldValues[field.id];
      const local = typeof current === 'string' ? current.trim() : '';
      return !!(local || initials.trim());
    }
    if (field.type === 'checkbox') return fieldValues[field.id] === true;
    const value = fieldValues[field.id];
    return typeof value === 'string' && value.trim().length > 0;
  };

  const getFieldRequiredTabSteps = (field: EnvelopeField) => requiredTabSteps.filter((step) => step.fieldId === field.id);

  const isRequiredTabStepCompleted = (step: RequiredTabStep) => Boolean(reviewedTabKeys[step.key]) && isFieldValueCompleted(step.field);

  const isFieldCompleted = (field: EnvelopeField) => {
    if (!isFieldValueCompleted(field)) return false;
    if (field.required === false) return true;
    const fieldSteps = getFieldRequiredTabSteps(field);
    return fieldSteps.length === 0 || fieldSteps.every(isRequiredTabStepCompleted);
  };

  const missingRequiredTabSteps = requiredTabSteps.filter((step) => !isRequiredTabStepCompleted(step));
  const missingRequiredFields = requiredAssignedFields.filter((field) => !isFieldCompleted(field));
  const completedAssignedFieldIds = assignedFields.filter((field) => isFieldCompleted(field)).map((field) => field.id);
  const completedRequiredTabKeys = requiredTabSteps.filter(isRequiredTabStepCompleted).map((step) => step.key);
  const missingRequiredTabKeys = missingRequiredTabSteps.map((step) => step.key);
  const reviewedRequiredTabCount = requiredTabSteps.filter((step) => reviewedTabKeys[step.key]).length;

  const requiredCompletionPercent =
    requiredTabSteps.length === 0
      ? 100
      : Math.round(((requiredTabSteps.length - missingRequiredTabSteps.length) / requiredTabSteps.length) * 100);
  const completedRequiredCount = requiredTabSteps.length - missingRequiredTabSteps.length;
  const disclosurePrimaryLabel = missingRequiredTabSteps.length > 0 ? 'Start Signing' : 'Review Final Signature';

  const interactionLocked = !rulesAcknowledged;
  const signerNameEntered = !!name.trim();
  const canCompleteNow =
    rulesAcknowledged && signerNameEntered && missingRequiredTabSteps.length === 0 && !submitting;
  const nextRequiredTabStep = missingRequiredTabSteps[0] || null;
  const nextRequiredField = nextRequiredTabStep?.field || null;
  const nextRequiredFieldIndex = nextRequiredField
    ? assignedFields.findIndex((field) => field.id === nextRequiredField.id)
    : -1;
  const nextRequiredRequiredIndex = nextRequiredField
    ? requiredTabSteps.findIndex((step) => step.key === nextRequiredTabStep?.key)
    : -1;
  const nextRequiredFieldLabel = nextRequiredField
    ? getFieldLabel(nextRequiredField, nextRequiredFieldIndex >= 0 ? nextRequiredFieldIndex : 0)
    : null;
  const nextRequiredFieldAssistText = nextRequiredField ? getFieldAssistText(nextRequiredField) : null;
  const guidanceEyebrow = interactionLocked
    ? 'Step 1 required'
    : nextRequiredTabStep
      ? `Next tab${nextRequiredRequiredIndex >= 0 ? ` ${nextRequiredRequiredIndex + 1}` : ''}`
      : 'Ready to finish';
  const guidanceHeadline = interactionLocked
    ? 'Unlock your signer tabs to begin.'
    : nextRequiredFieldLabel && nextRequiredTabStep
      ? `Review ${nextRequiredFieldLabel} on page ${nextRequiredTabStep.pageNumber}.`
      : signerNameEntered
        ? 'Everything assigned to you is complete.'
        : 'One last step: type your legal name, then finish.';
  const guidanceBody = interactionLocked
    ? 'Open the disclosure prompt first. That unlocks your tabs, packet actions, and final signature confirmation.'
    : nextRequiredTabStep
      ? nextRequiredFieldAssistText || `Jump to page ${nextRequiredTabStep.pageNumber}, review the highlighted tab, then continue to the next one.`
      : signerNameEntered
        ? 'Your tabs are ready. Review your adopted signature style or finish the packet when you are comfortable.'
        : 'Your required tabs are complete. Type your full legal name below so the final signature can be captured.';
  const adoptModalTitle = adoptModalMode === 'initials' ? 'Adopt initials' : 'Adopt signature & initials';
  const adoptModalSubtitle =
    adoptModalMode === 'finalize'
      ? 'Confirm your adopted signature before final submit'
      : adoptModalMode === 'signature'
        ? 'Apply your adopted signature to this signer tab'
        : 'Apply your adopted initials anywhere this packet needs them';
  const adoptModalPrimaryLabel =
    adoptModalMode === 'finalize'
      ? 'Adopt and Sign'
      : adoptModalMode === 'signature'
        ? 'Apply Signature'
        : 'Apply Initials';
  const mobilePrimaryLabel =
    missingRequiredTabSteps.length > 0
      ? `Next Tab (${missingRequiredTabSteps.length})`
      : submitting
        ? 'Finalizing…'
        : 'Complete Now';

  const signerTasks = [
    {
      id: 'ack',
      label: 'Acknowledge e-sign disclosure',
      done: rulesAcknowledged,
      detail: 'Required first to unlock your signer tabs.',
    },
    {
      id: 'fields',
      label: 'Review highlighted tabs',
      done: requiredTabSteps.length > 0 ? missingRequiredTabSteps.length === 0 : true,
      detail:
        requiredTabSteps.length > 0
          ? `${completedRequiredCount}/${requiredTabSteps.length} reviewed`
          : 'No required fields assigned',
    },
    {
      id: 'adopt',
      label: 'Type legal name and finish',
      done: !!hash,
      detail: signerNameEntered ? 'Ready to complete signature.' : 'Type your full legal name below.',
    },
  ];

  const nextSignerTask = signerTasks.find((task) => !task.done);
  const signerDisplayName = data?.signer?.name || name || 'Signer';
  const packetDisplayName = data?.packetTitle || propertyAddress || 'Contract packet';
  const summaryStats = [
    {
      label: 'Signer',
      value: signerDisplayName,
      detail: signerRoleLabel,
    },
    {
      label: 'Required',
      value: `${completedRequiredCount}/${requiredTabSteps.length || 0}`,
      detail: missingRequiredTabSteps.length > 0 ? `${missingRequiredTabSteps.length} tabs left` : 'All complete',
    },
    {
      label: 'Next step',
      value: nextSignerTask?.label || 'Ready to sign',
      detail: interactionLocked ? 'Start with disclosure' : canCompleteNow ? 'Finalize signature' : 'Follow guided steps',
    },
  ];
  const disclosureSummary = [
    {
      label: 'Signer',
      value: signerDisplayName,
      detail: signerRoleLabel,
    },
    {
      label: 'Packet',
      value: packetDisplayName,
      detail: 'Secure signer link',
    },
    {
      label: 'Signing',
      value: 'Typed name = legal signature',
      detail: 'Only your tabs are active',
    },
  ];
  const disclosureHighlights = [
    'No app or account required',
    'Phone and desktop friendly',
    'Only your tabs unlock here',
  ];
  const disclosureSteps = [
    {
      step: '1',
      title: 'Review highlighted tabs',
      detail: 'Only the tabs assigned to your role can be completed from this secure link.',
    },
    {
      step: '2',
      title: 'Adopt your name and initials',
      detail: 'You confirm them once, then reuse them anywhere this packet needs them.',
    },
    {
      step: '3',
      title: 'Finish with one confirmation',
      detail: 'Your completion is stored with a secure audit trail for compliance records.',
    },
  ];

  const markTabStepReviewed = (tabKey?: string | null) => {
    if (!tabKey) return;
    setReviewedTabKeys((prev) => (prev[tabKey] ? prev : { ...prev, [tabKey]: true }));
  };

  const openAdoptModal = (mode: 'finalize' | 'signature' | 'initials', field?: EnvelopeField, tabKey?: string | null) => {
    const suggestedName = name.trim() || data?.signer?.name || '';
    const suggestedInitials = initials.trim() || deriveInitials(suggestedName);

    if (!name.trim() && suggestedName) {
      setName(suggestedName);
    }
    if (!initials.trim() && suggestedInitials) {
      setInitials(suggestedInitials);
    }
    if (field) {
      setActiveRequiredFieldId(field.id);
    }
    if (tabKey) {
      setActiveRequiredTabKey(tabKey);
      markTabStepReviewed(tabKey);
    }

    setFormError(null);
    setAdoptModalMode(mode);
    setShowAdoptModal(true);
  };

  const closeAdoptModal = () => {
    setShowAdoptModal(false);
    setAdoptModalMode('finalize');
  };

  const focusField = (field: EnvelopeField) => {
    setActiveRequiredFieldId(field.id);
    if (field.type === 'signature') {
      nameInputRef.current?.focus();
      nameInputRef.current?.scrollIntoView({ behavior: 'smooth', block: 'center' });
      return;
    }
    const target = fieldInputRefs.current[field.id];
    target?.focus();
    target?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  };

  const getPreferredTabStep = (field: EnvelopeField) =>
    missingRequiredTabSteps.find((step) => step.fieldId === field.id) ||
    requiredTabSteps.find((step) => step.fieldId === field.id) ||
    null;

  const activateTabStep = (step: RequiredTabStep) => {
    if (interactionLocked) {
      setShowDisclosurePrompt(true);
      return;
    }

    setActiveRequiredFieldId(step.fieldId);
    setActiveRequiredTabKey(step.key);
    markTabStepReviewed(step.key);

    if ((step.field.type === 'signature' || step.field.type === 'initials') && !isFieldValueCompleted(step.field)) {
      openAdoptModal(step.field.type, step.field, step.key);
      return;
    }

    if (!['signature', 'initials'].includes(step.field.type)) {
      focusField(step.field);
    }
  };

  const activateField = (field: EnvelopeField) => {
    if (interactionLocked) {
      setShowDisclosurePrompt(true);
      return;
    }

    const targetStep = getPreferredTabStep(field);
    if (targetStep) {
      activateTabStep(targetStep);
      return;
    }

    if (field.type === 'signature' || field.type === 'initials') {
      openAdoptModal(field.type, field);
      return;
    }

    focusField(field);
  };

  const closeDisclosurePrompt = () => {
    if (!rulesAcknowledged) return;
    if (hasSuggestedDefaults) {
      applySmartFieldAutofill(false);
    }
    setShowDisclosurePrompt(false);
    setFormError(null);

    requestAnimationFrame(() => {
      if (missingRequiredTabSteps.length > 0) {
        activateTabStep(missingRequiredTabSteps[0]);
        return;
      }
      nameInputRef.current?.focus();
    });
  };

  const applySmartFieldAutofill = (force = false) => {
    const suggestedName = name.trim() || data?.signer?.name || '';
    const suggestedInitials = deriveInitials(suggestedName);
    const suggestedDate = new Date().toISOString().slice(0, 10);

    if (suggestedInitials && (force || !initials.trim()) && suggestedInitials !== initials.trim()) {
      setInitials(suggestedInitials);
    }

    setFieldValues((prev) => {
      const next = { ...prev };
      let didChange = false;

      assignedFields.forEach((field) => {
        if (!field?.id) return;

        const currentValue = next[field.id];
        const hasCurrentValue =
          field.type === 'checkbox'
            ? currentValue === true
            : typeof currentValue === 'string' && currentValue.trim().length > 0;
        if (hasCurrentValue && !force) return;

        if (field.type === 'initials') {
          if (suggestedInitials && currentValue !== suggestedInitials) {
            next[field.id] = suggestedInitials;
            didChange = true;
          }
          return;
        }
        if (field.type === 'name') {
          if (suggestedName && currentValue !== suggestedName) {
            next[field.id] = suggestedName;
            didChange = true;
          }
          return;
        }
        if (field.type === 'email') {
          if (signerEmail && currentValue !== signerEmail) {
            next[field.id] = signerEmail;
            didChange = true;
          }
          return;
        }
        if (field.type === 'address') {
          if (propertyAddress && currentValue !== propertyAddress) {
            next[field.id] = propertyAddress;
            didChange = true;
          }
          return;
        }
        if (field.type === 'date') {
          if (currentValue !== suggestedDate) {
            next[field.id] = suggestedDate;
            didChange = true;
          }
          return;
        }
        if (field.type === 'price') {
          if (contractSnapshot.purchasePrice !== undefined && contractSnapshot.purchasePrice !== null) {
            const suggestedPrice = String(contractSnapshot.purchasePrice);
            if (currentValue !== suggestedPrice) {
              next[field.id] = suggestedPrice;
              didChange = true;
            }
          }
          return;
        }
        if (field.type === 'mls') {
          if (contractSnapshot.mlsId) {
            const suggestedMls = String(contractSnapshot.mlsId);
            if (currentValue !== suggestedMls) {
              next[field.id] = suggestedMls;
              didChange = true;
            }
          }
        }
      });

      return didChange ? next : prev;
    });
  };

  const applyAdoptedSignerMarks = () => {
    const adoptedName = name.trim() || data?.signer?.name?.trim() || '';
    const adoptedInitials = initials.trim() || deriveInitials(adoptedName);

    if (!adoptedName) {
      setFormError('Enter your full legal name before continuing.');
      return null;
    }

    if (!adoptedInitials) {
      setFormError('Please set your initials before continuing.');
      return null;
    }

    if (adoptedName !== name.trim()) {
      setName(adoptedName);
    }
    if (adoptedInitials !== initials.trim()) {
      setInitials(adoptedInitials);
    }

    setFieldValues((prev) => {
      const next = { ...prev };
      let didChange = false;

      assignedFields.forEach((field) => {
        if (field.type === 'initials' && next[field.id] !== adoptedInitials) {
          next[field.id] = adoptedInitials;
          didChange = true;
        }
        if (field.type === 'name' && next[field.id] !== adoptedName) {
          next[field.id] = adoptedName;
          didChange = true;
        }
      });

      return didChange ? next : prev;
    });

    setFormError(null);
    return { adoptedInitials };
  };

  const goToNextMissingField = () => {
    if (missingRequiredTabSteps.length === 0) return;
    const currentIndex = activeRequiredTabKey
      ? requiredTabSteps.findIndex((step) => step.key === activeRequiredTabKey)
      : -1;
    const nextStep =
      missingRequiredTabSteps.find((step) => requiredTabSteps.findIndex((candidate) => candidate.key === step.key) > currentIndex) ||
      missingRequiredTabSteps[0];
    activateTabStep(nextStep);
  };

  useEffect(() => {
    if (missingRequiredTabSteps.length === 0) {
      return;
    }
    if (!activeRequiredTabKey) {
      setActiveRequiredFieldId(missingRequiredTabSteps[0].fieldId);
      setActiveRequiredTabKey(missingRequiredTabSteps[0].key);
    }
  }, [activeRequiredTabKey, missingRequiredTabSteps]);

  useEffect(() => {
    const syncViewport = () => {
      setIsCompactMobile(window.matchMedia('(max-width: 960px)').matches);
    };

    syncViewport();
    window.addEventListener('resize', syncViewport);
    return () => window.removeEventListener('resize', syncViewport);
  }, []);

  const buildCompletedAssignedFields = (effectiveInitials: string) =>
    assignedFields.map((field) => {
      const localValue = fieldValues[field.id];
      if (field.type === 'signature') {
        return { id: field.id, type: field.type, value: name.trim() };
      }
      if (field.type === 'initials') {
        const initialsValue =
          typeof localValue === 'string' && localValue.trim() ? localValue.trim() : effectiveInitials;
        return { id: field.id, type: field.type, value: initialsValue };
      }
      if (field.type === 'checkbox') {
        return { id: field.id, type: field.type, value: localValue === true ? 'checked' : '' };
      }
      return {
        id: field.id,
        type: field.type,
        value: typeof localValue === 'string' ? localValue : '',
      };
    });

  useEffect(() => {
    const load = async () => {
      if (!envelopeId || !signerId || !token) return;
      try {
        const res = await api.get(`/esign-public/envelopes/${envelopeId}/${signerId}/${token}`);
        setData({
          contractSnapshot: res.data?.contractSnapshot ?? {},
          envelopeType: res.data?.envelopeType,
          packetTitle: res.data?.packetTitle,
          signer: res.data?.signer
            ? {
                id: res.data.signer.id,
                name: res.data.signer.name,
                email: res.data.signer.email,
                role: res.data.signer.role,
              }
            : undefined,
          signers: Array.isArray(res.data?.signers)
            ? res.data.signers.map((participant: any) => ({
                id: participant.id,
                name: participant.name,
                role: participant.role,
                signedAt: participant.signedAt,
              }))
            : undefined,
        });
        setName(res.data?.signer?.name || '');

        const incomingFields: EnvelopeField[] = Array.isArray(res.data?.contractSnapshot?.__esignFieldPlacements)
          ? res.data.contractSnapshot.__esignFieldPlacements
          : [];
        const initialValues: Record<string, string | boolean> = {};
        incomingFields.forEach((field) => {
          if (!field?.id) return;
          if (field.type === 'checkbox') {
            initialValues[field.id] = field.value === 'checked';
            return;
          }
          initialValues[field.id] = field.value || '';
        });
        setFieldValues(initialValues);
        setReviewedTabKeys({});
        setActiveRequiredFieldId(null);
        setActiveRequiredTabKey(null);
      } catch (err) {
        console.error('Failed to load envelope:', err);
        setError('This signing link is invalid or has expired.');
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [envelopeId, signerId, token]);

  useEffect(() => {
    if (!name.trim()) return;
    if (initials.trim()) return;
    const suggested = deriveInitials(name);
    if (suggested) {
      setInitials(suggested);
    }
  }, [name, initials]);

  useEffect(() => {
    if (!data || !hasSuggestedDefaults) return;
    applySmartFieldAutofill(false);
  }, [
    data,
    name,
    signerEmail,
    propertyAddress,
    contractSnapshot.purchasePrice,
    contractSnapshot.mlsId,
    hasSuggestedDefaults,
    autofillFieldSignature,
  ]);

  useEffect(() => {
    setPdfReady(false);
  }, [packetPdfPath]);

  const performSubmit = async ({ initialsOverride }: { initialsOverride?: string } = {}) => {
    if (!envelopeId || !signerId || !token) return;
    setSubmitting(true);
    setFormError(null);
    try {
      const effectiveInitials = (initialsOverride ?? initials).trim();
      const completedAssignedFields = buildCompletedAssignedFields(effectiveInitials);
      const res = await api.post(`/esign-public/sign/${envelopeId}/${signerId}/${token}`, {
        name,
        signatureType: 'TYPED',
        acceptedEsignRules: rulesAcknowledged,
        signatureData: {
          fullName: name,
          initials: effectiveInitials,
          style: signatureStyle,
          adoptedAt: new Date().toISOString(),
          rulesAcknowledged,
          rulesAcknowledgedAt: new Date().toISOString(),
          completedFields: completedAssignedFields,
        },
        completedFields: completedAssignedFields,
      });
      setSignedAt(new Date().toISOString());
      setHash(res.data.auditHash);
    } catch (err: any) {
      const status = err?.response?.status;
      const serverError = err?.response?.data?.error;

      if (status === 409 && serverError === 'Already signed') {
        setFormError('This document has already been signed with this link.');
      } else if (status === 401) {
        setFormError('This signing link is invalid or has expired.');
      } else {
        setFormError(serverError || 'Unable to capture signature. Please try again.');
      }
    } finally {
      setSubmitting(false);
    }
  };

  const handleSubmit = async () => {
    setFormError(null);
    if (!rulesAcknowledged) {
      setShowDisclosurePrompt(true);
      setFormError('Please accept the e-sign disclosure before signing.');
      return;
    }
    if (missingRequiredTabSteps.length > 0) {
      setFormError(`Please review every required signing tab before signing (${missingRequiredTabSteps.length} remaining).`);
      goToNextMissingField();
      return;
    }
    if (!name.trim()) {
      setFormError('Enter your full legal name before signing.');
      return;
    }
    openAdoptModal('finalize');
  };

  const handleQuickComplete = async () => {
    setFormError(null);
    if (!rulesAcknowledged) {
      setShowDisclosurePrompt(true);
      setFormError('Please accept the e-sign disclosure before signing.');
      return;
    }
    if (missingRequiredTabSteps.length > 0) {
      setFormError(`Please review every required signing tab before signing (${missingRequiredTabSteps.length} remaining).`);
      goToNextMissingField();
      return;
    }
    if (!name.trim()) {
      setFormError('Enter your full legal name before signing.');
      return;
    }

    const effectiveInitials = initials.trim() || deriveInitials(name);
    if (!initials.trim() && effectiveInitials) {
      setInitials(effectiveInitials);
    }
    await performSubmit({ initialsOverride: effectiveInitials });
  };

  const handleConfirmAdoptAndSign = async () => {
    const adopted = applyAdoptedSignerMarks();
    if (!adopted) return;

    if (adoptModalMode === 'finalize') {
      closeAdoptModal();
      await performSubmit({ initialsOverride: adopted.adoptedInitials });
      return;
    }

    closeAdoptModal();
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center ae-bg">
        <div className="text-sm text-slate-400">Loading e-sign packet…</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center ae-bg px-4">
        <Card tone="solid" className="max-w-md w-full p-6 space-y-3 text-sm bg-slate-900/40 backdrop-blur-xl border-white/10">
          <div className="text-lg font-semibold text-white">Unable to continue signing</div>
          <div className="text-slate-400">{error}</div>
        </Card>
      </div>
    );
  }

  if (hash) {
    return (
      <div className="min-h-screen flex items-center justify-center ae-bg px-4 relative overflow-hidden">
        <div className="ae-bg-gradient absolute inset-0" />
        <div className="ae-bg-wave absolute inset-0 opacity-30" />

        <Card tone="solid" className="relative z-10 max-w-2xl w-full p-6 md:p-8 space-y-6 text-sm bg-slate-900/40 backdrop-blur-xl border-white/10">
          <div className="flex flex-col items-center text-center space-y-3">
            <div className="h-14 w-14 rounded-full bg-emerald-500/20 flex items-center justify-center text-emerald-400 shadow-lg shadow-emerald-500/10">
              <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
            </div>
            <h1 className="text-xl font-bold text-white md:text-2xl">Signature complete</h1>
            <p className="max-w-xl text-slate-300">
              Your signature has been recorded with a secure audit trail. This signer step is finished, and you can close this window at any time.
            </p>
          </div>

          <div className="grid gap-3 md:grid-cols-3">
            <div className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3">
              <div className="text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-500">Signer</div>
              <div className="mt-1 text-sm font-semibold leading-6 text-white">{signerDisplayName}</div>
              <div className="mt-1 text-xs text-slate-400">{signerRoleLabel}</div>
            </div>
            <div className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3">
              <div className="text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-500">Property</div>
              <div className="mt-1 text-sm font-semibold leading-6 text-white">{packetDisplayName}</div>
              <div className="mt-1 text-xs text-slate-400">Signed and sealed</div>
            </div>
            <div className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3">
              <div className="text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-500">Recorded</div>
              <div className="mt-1 text-sm font-semibold leading-6 text-white">{signedAt ? new Date(signedAt).toLocaleString() : 'Just now'}</div>
              <div className="mt-1 text-xs text-slate-400">Secure audit trail captured</div>
            </div>
          </div>

          <div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-50">
            <span className="font-semibold text-white">What happens next:</span>{' '}
            {otherPendingRoles.length > 0
              ? `${otherPendingRoles.map((role) => getRoleLabel(role)).join(' and ')} can continue from their own secure signing links.`
              : 'This link is fully complete and your signed record is safely stored.'}
          </div>

          <div className="rounded-2xl border border-white/10 bg-white/5 p-4">
            <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
              <div>
                <p className="text-[10px] text-slate-500 uppercase tracking-wide font-bold mb-1">Audit trail</p>
                <p className="text-sm text-slate-300 max-w-xl">
                  A secure signing receipt has been recorded for this signature and is available to the sender for compliance records.
                </p>
              </div>
              <div className="flex items-center gap-2">
                {packetPdfDownloadPath && (
                  <a
                    href={packetPdfDownloadPath}
                    target="_blank"
                    rel="noreferrer"
                    className="inline-flex items-center justify-center rounded-xl bg-white text-slate-900 px-3 py-2 text-xs font-semibold shadow-lg shadow-white/10"
                  >
                    Download Packet
                  </a>
                )}
              </div>
            </div>
          </div>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-start md:items-center justify-center ae-bg px-3 md:px-4 pt-3 md:pt-0 pb-24 md:pb-4 relative overflow-hidden">
      <div className="ae-bg-gradient absolute inset-0" />
      <div className="ae-bg-wave absolute inset-0 opacity-30" />

      <Card
        tone="solid"
        className={`relative z-10 w-[98vw] max-w-[1500px] p-4 md:p-6 lg:p-8 space-y-6 text-sm bg-slate-900/40 backdrop-blur-xl border-white/10 ${
          isCompactMobile ? 'pb-24' : ''
        } ${
          showDisclosurePrompt ? 'pointer-events-none blur-[3px] saturate-75 scale-[0.995] transition-all' : 'transition-all'
        }`}
      >
        <div className="space-y-5">
          <div className="space-y-2">
            <h1 className="text-[2rem] font-bold tracking-tight text-white md:text-[2.35rem]">Review and sign</h1>
            <p className="max-w-3xl text-sm leading-7 text-slate-300 md:text-base">
              Review the contract packet, complete only the fields assigned to you, and finish with one final signature confirmation.
            </p>
          </div>

          <div className="grid gap-3 md:grid-cols-3">
            {summaryStats.map((item) => (
              <div key={item.label} className="rounded-2xl border border-white/10 bg-white/5 px-5 py-4">
                <div className="text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-400">{item.label}</div>
                <div className="mt-1 text-base font-semibold leading-6 text-white">{item.value}</div>
                <div className="mt-1 text-xs leading-5 text-slate-400">{item.detail}</div>
              </div>
            ))}
          </div>
        </div>

        <div className={`rounded-2xl border px-5 py-4 ${rulesAcknowledged ? 'border-emerald-500/40 bg-emerald-500/10' : 'border-amber-500/40 bg-amber-500/10'}`}>
          <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
            <div>
              <div className="text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-300">
                {rulesAcknowledged ? 'E-sign disclosure accepted' : 'E-sign disclosure required'}
              </div>
              <div className="mt-1 text-sm leading-6 text-slate-200">
                {rulesAcknowledged
                  ? 'The packet is unlocked. Review your tabs, confirm your legal name, and complete the signature step when ready.'
                  : 'Open the disclosure prompt, check the acknowledgement box, and continue to unlock every signing action.'}
              </div>
            </div>
            <Button type="button" variant="outline" size="sm" onClick={() => setShowDisclosurePrompt(true)}>
              {rulesAcknowledged ? 'Review Disclosure' : 'Open Disclosure'}
            </Button>
          </div>
        </div>

        <div
          className={`rounded-2xl border px-4 py-4 ${
            interactionLocked
              ? 'border-amber-500/30 bg-amber-500/10'
              : 'border-cyan-500/30 bg-cyan-500/10'
          }`}
        >
          <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between">
            <div className="space-y-2">
              <div className="flex flex-wrap items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.16em]">
                <span
                  className={`rounded-full px-3 py-1 ${
                    interactionLocked
                      ? 'border border-amber-400/35 bg-amber-300/10 text-amber-100'
                      : 'border border-cyan-400/35 bg-cyan-300/10 text-cyan-100'
                  }`}
                >
                  {guidanceEyebrow}
                </span>
                <span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-slate-200">
                  {requiredCompletionPercent}% ready
                </span>
                {!interactionLocked && nextRequiredFieldLabel && (
                  <span className="rounded-full border border-white/10 bg-slate-950/40 px-3 py-1 text-slate-300">
                    {nextRequiredFieldLabel}
                  </span>
                )}
              </div>

              <div className="text-lg font-semibold tracking-tight text-white">{guidanceHeadline}</div>
              <div className="max-w-3xl text-sm leading-6 text-slate-200/90">{guidanceBody}</div>
            </div>

            <div className="flex flex-wrap gap-2">
              {hasSuggestedDefaults && !interactionLocked && (
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={() => applySmartFieldAutofill(false)}
                >
                  Autofill Tabs
                </Button>
              )}

              {interactionLocked ? (
                <Button type="button" size="sm" onClick={() => setShowDisclosurePrompt(true)}>
                  Unlock Packet
                </Button>
              ) : nextRequiredField ? (
                <Button type="button" size="sm" onClick={goToNextMissingField}>
                  Go to Next Tab
                </Button>
              ) : (
                <Button type="button" size="sm" onClick={handleSubmit} disabled={!canCompleteNow}>
                  Finish Packet
                </Button>
              )}
            </div>
          </div>
        </div>

        {(autoGeneratedPlan || otherPendingRoles.length > 0) && (
          <div className="rounded-2xl border border-cyan-500/30 bg-cyan-500/10 px-5 py-4 text-sm leading-6 text-cyan-50">
            <span className="font-semibold text-white">Only your tabs are active in this link.</span>{' '}
            {autoGeneratedPlan
              ? `${signerRoleLabel} initials will be applied everywhere required for your role, and your final signature is captured once on the final signature line.`
              : `Only the fields assigned to ${signerRoleLabel.toLowerCase()} are actionable here.`}
            {otherPendingRoles.length > 0
              ? ` ${otherPendingRoles.map((role) => getRoleLabel(role)).join(' and ')} tabs remain inactive until those signers open their own links.`
              : ''}
          </div>
        )}

        <div className={`grid gap-4 ${focusPdf ? 'grid-cols-1' : 'xl:grid-cols-[minmax(0,2.3fr)_minmax(22rem,1fr)]'}`}>
          <div className="rounded-2xl border border-white/10 bg-black/20 overflow-hidden min-h-[620px] relative">
            <div className="flex items-center justify-between gap-2 px-4 py-3 border-b border-white/10 bg-slate-900/60">
              <div className="text-xs leading-5 text-slate-300 md:text-sm">
                Zoom tip: use PDF controls (+/-) for exact line review.
              </div>
              <div className="flex items-center gap-2">
                <Button type="button" variant="outline" size="sm" disabled={interactionLocked} onClick={() => setFocusPdf((v) => !v)}>
                  {focusPdf ? 'Show Signing Panel' : 'Focus PDF'}
                </Button>
                <Button type="button" variant="outline" size="sm" disabled={interactionLocked} onClick={() => setShowPdfFullscreen(true)}>
                  Full Screen
                </Button>
              </div>
            </div>

            {!pdfReady && (
              <div className="absolute inset-0 z-10 flex items-center justify-center text-slate-300 text-sm bg-slate-900/30">
                Loading contract PDF…
              </div>
            )}

            {packetPdfPath ? (
              <InteractivePacketViewer
                pdfUrl={packetPdfPath}
                envelopeType={data?.envelopeType}
                signerRole={signerRole}
                fields={assignedFields}
                activeFieldId={activeRequiredFieldId}
                activeHotspotKey={activeRequiredTabKey}
                missingFieldIds={missingRequiredFields.map((field) => field.id)}
                missingHotspotKeys={missingRequiredTabKeys}
                completedFieldIds={completedAssignedFieldIds}
                completedHotspotKeys={completedRequiredTabKeys}
                disabled={interactionLocked}
                onReadyChange={setPdfReady}
                onActivateField={(fieldId, hotspotKey) => {
                  const targetField = assignedFields.find((field) => field.id === fieldId);
                  if (!targetField) return;
                  const targetStep = requiredTabSteps.find((step) => step.key === hotspotKey);
                  if (targetStep) {
                    activateTabStep(targetStep);
                    return;
                  }
                  activateField(targetField);
                }}
              />
            ) : (
              <div className="h-full min-h-[620px] flex items-center justify-center text-slate-400 text-sm px-4 text-center">
                PDF preview unavailable. You can still complete signature from the panel.
              </div>
            )}

            {!interactionLocked && (
              <div className="absolute bottom-3 left-3 right-3 z-20 pointer-events-none">
                <div className="pointer-events-auto rounded-2xl border border-slate-900/50 bg-slate-950/80 backdrop-blur-xl p-3 shadow-2xl shadow-slate-950/70">
                  <div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between">
                    <div>
                      <div className="text-[10px] uppercase tracking-[0.16em] text-cyan-200 font-semibold">Guided signing</div>
                      <div className="text-sm leading-6 text-slate-200">
                        {missingRequiredTabSteps.length > 0
                          ? `${missingRequiredTabSteps.length} required tab${missingRequiredTabSteps.length > 1 ? 's' : ''} left. Jump directly to the next one.`
                          : 'All required tabs are complete. You are ready to finalize signature.'}
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      {hasSuggestedDefaults && (
                        <Button
                          type="button"
                          variant="outline"
                          size="sm"
                          onClick={() => applySmartFieldAutofill(false)}
                          disabled={interactionLocked}
                        >
                          {autofillActionLabel}
                        </Button>
                      )}
                      <Button
                        type="button"
                        size="sm"
                        onClick={goToNextMissingField}
                        disabled={interactionLocked || missingRequiredTabSteps.length === 0}
                      >
                        Next Tab
                      </Button>
                    </div>
                  </div>

                  {missingRequiredTabSteps.length > 0 && (
                    <div className="mt-2 flex flex-wrap gap-2">
                      {missingRequiredTabSteps.slice(0, 4).map((step, idx) => {
                        const field = step.field;
                        const requiredIndex = requiredTabSteps.findIndex((requiredStep) => requiredStep.key === step.key);
                        return (
                          <button
                            key={step.key}
                            type="button"
                            onClick={() => activateTabStep(step)}
                            className="rounded-lg border border-cyan-400/40 bg-cyan-500/10 px-2.5 py-1.5 text-xs font-semibold text-cyan-100 hover:bg-cyan-500/20"
                          >
                            {requiredIndex >= 0 ? requiredIndex + 1 : idx + 1}. {getFieldLabel(field, idx)} · p.{step.pageNumber}
                          </button>
                        );
                      })}
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>

          {!focusPdf && (
            <div className="space-y-3 xl:sticky xl:top-4 self-start">
              <div className="rounded-2xl border border-white/10 bg-white/5 p-4">
                <div className="mb-3 text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-400">Packet details</div>
                <div className="space-y-2 text-sm leading-6 text-slate-200">
                  <div>Form: {data?.envelopeType || 'Contract packet'}</div>
                  <div>Property: {packetDisplayName}</div>
                  {formatMoney(contractSnapshot.purchasePrice) && <div>Purchase price: {formatMoney(contractSnapshot.purchasePrice)}</div>}
                  {contractSnapshot.buyerNames && <div>Buyer: {contractSnapshot.buyerNames}</div>}
                  {contractSnapshot.sellerNames && <div>Seller: {contractSnapshot.sellerNames}</div>}
                  <div>Signer role: {signerRoleLabel}</div>
                </div>
              </div>

              <div className="rounded-2xl border border-cyan-500/25 bg-cyan-500/10 p-4">
                <div className="mb-3 text-[10px] font-semibold uppercase tracking-[0.16em] text-cyan-200">Your signing steps</div>
                <div className="space-y-3">
                  {signerTasks.map((task, idx) => (
                    <div key={task.id} className="flex items-start gap-2 text-sm">
                      <div className={`mt-0.5 inline-flex h-6 w-6 items-center justify-center rounded-full border text-[11px] font-bold ${task.done ? 'border-emerald-400/50 bg-emerald-500/20 text-emerald-200' : 'border-white/20 bg-white/5 text-slate-300'}`}>
                        {task.done ? '✓' : idx + 1}
                      </div>
                      <div className="min-w-0">
                        <div className={`${task.done ? 'text-emerald-200' : 'text-slate-100'} font-semibold leading-6`}>{task.label}</div>
                        <div className="text-slate-400 leading-6">{task.detail}</div>
                      </div>
                    </div>
                  ))}
                </div>
                {packetPdfPath && (
                  <div className="mt-4 flex items-center gap-3">
                    <a
                      href={packetPdfPath}
                      target="_blank"
                      rel="noreferrer"
                      className={`text-sm font-semibold underline ${interactionLocked ? 'text-slate-400 pointer-events-none' : 'text-cyan-100'}`}
                    >
                      Open PDF in new tab
                    </a>
                    {packetPdfDownloadPath && (
                      <a
                        href={packetPdfDownloadPath}
                        className={`text-sm font-semibold underline ${interactionLocked ? 'text-slate-400 pointer-events-none' : 'text-cyan-100'}`}
                      >
                        Download PDF
                      </a>
                    )}
                  </div>
                )}
              </div>

              <div className="space-y-3 rounded-2xl border border-white/10 bg-white/5 p-4">
                {assignedFields.length > 0 && (
                  <div className="space-y-3 rounded-xl border border-white/10 bg-slate-900/50 p-4">
                    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                      <div>
                        <label className="block text-[10px] font-semibold text-slate-400 uppercase tracking-[0.16em]">
                          Your tabs
                        </label>
                        <div className="mt-1 text-sm leading-6 text-slate-200">
                          {missingRequiredTabSteps.length > 0
                            ? `${missingRequiredTabSteps.length} tab${missingRequiredTabSteps.length > 1 ? 's' : ''} still need your attention.`
                            : 'Everything assigned to you is ready.'}
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        <span className="text-xs text-slate-400">
                          {reviewedRequiredTabCount}/{requiredTabSteps.length} visited
                        </span>
                        {hasSuggestedDefaults && (
                          <button
                            type="button"
                            onClick={() => applySmartFieldAutofill(false)}
                            disabled={interactionLocked}
                            className="rounded-md border border-white/10 px-2.5 py-1.5 text-xs font-semibold text-slate-200 hover:bg-white/10 disabled:opacity-50"
                          >
                            {autofillActionLabel}
                          </button>
                        )}
                        <button
                          type="button"
                          onClick={goToNextMissingField}
                          disabled={interactionLocked || missingRequiredTabSteps.length === 0}
                          className="rounded-md border border-white/10 px-2.5 py-1.5 text-xs font-semibold text-slate-200 hover:bg-white/10 disabled:opacity-50"
                        >
                          Next Tab
                        </button>
                      </div>
                    </div>

                    <div className="h-1.5 rounded-full bg-white/10 overflow-hidden">
                      <div
                        className="h-full rounded-full bg-emerald-500 transition-all"
                        style={{ width: `${requiredCompletionPercent}%` }}
                      />
                    </div>

                    <div className="space-y-2 max-h-56 overflow-auto pr-1">
                      {assignedFields.map((field, index) => {
                        const label = getFieldLabel(field, index);
                        const key = `${field.id}-${index}`;
                        const completed = isFieldCompleted(field);
                        const requiredIndex = requiredAssignedFields.findIndex((requiredField) => requiredField.id === field.id);
                        const indexBadge = requiredIndex >= 0 ? requiredIndex + 1 : null;
                        const isActive = activeRequiredFieldId === field.id;
                        const assistText = getFieldAssistText(field);

                        if (field.type === 'checkbox') {
                          return (
                            <label key={key} className={`flex items-start gap-2 rounded-lg border px-3 py-2.5 ${isActive ? 'border-cyan-400/60 bg-cyan-500/10' : 'border-white/10 bg-white/5'}`}>
                              {indexBadge && (
                                <span className="mt-0.5 inline-flex h-5 min-w-5 items-center justify-center rounded-full bg-slate-800 text-[10px] font-bold text-slate-300 px-1">
                                  {indexBadge}
                                </span>
                              )}
                              <input
                                type="checkbox"
                                ref={(el) => {
                                  fieldInputRefs.current[field.id] = el;
                                }}
                                disabled={interactionLocked}
                                checked={fieldValues[field.id] === true}
                                onChange={(e) => setFieldValues((prev) => ({ ...prev, [field.id]: e.target.checked }))}
                                className="mt-0.5 rounded border-slate-600 bg-slate-800 text-blue-500 focus:ring-blue-500"
                              />
                              <span className="text-sm text-slate-200">
                                <span className="block">
                                  {label}
                                  {field.required !== false && <span className="text-amber-300"> *</span>}
                                  <span className={`ml-2 text-xs ${completed ? 'text-emerald-300' : 'text-slate-500'}`}>
                                    {completed ? 'Done' : 'Required'}
                                  </span>
                                </span>
                                {assistText && <span className="mt-1 block text-xs text-slate-400">{assistText}</span>}
                              </span>
                              <button
                                type="button"
                                className="ml-auto text-xs font-semibold text-cyan-200 underline"
                                disabled={interactionLocked}
                                onClick={(e) => {
                                  e.preventDefault();
                                  activateField(field);
                                }}
                              >
                                Jump
                              </button>
                            </label>
                          );
                        }

                        if (field.type === 'signature') {
                          return (
                            <div key={key} className={`rounded-lg border px-3 py-2.5 text-sm text-slate-200 ${isActive ? 'border-cyan-400/60 bg-cyan-500/10' : 'border-white/10 bg-white/5'}`}>
                              <div className="flex items-center justify-between">
                                <span className="flex items-center gap-2">
                                  {indexBadge && (
                                    <span className="inline-flex h-5 min-w-5 items-center justify-center rounded-full bg-slate-800 text-[10px] font-bold text-slate-300 px-1">
                                      {indexBadge}
                                    </span>
                                  )}
                                  {label}
                                  {field.required !== false && <span className="text-amber-300"> *</span>}
                                </span>
                                <div className="flex items-center gap-2">
                                  <span className={`text-xs ${completed ? 'text-emerald-300' : 'text-slate-500'}`}>
                                    {completed ? 'Ready' : 'Open signing modal'}
                                  </span>
                                  <button
                                    type="button"
                                    className="text-xs font-semibold text-cyan-200 underline"
                                    disabled={interactionLocked}
                                    onClick={() => activateField(field)}
                                  >
                                    {completed ? 'Edit' : 'Adopt'}
                                  </button>
                                </div>
                              </div>
                              {assistText && <div className="mt-1 text-xs text-slate-400">{assistText}</div>}
                            </div>
                          );
                        }

                        if (field.type === 'initials') {
                          return (
                            <div key={key} className={`space-y-1 rounded-lg border px-3 py-2.5 ${isActive ? 'border-cyan-400/60 bg-cyan-500/10' : 'border-white/10 bg-white/5'}`}>
                              <label className="text-sm text-slate-300 flex items-center justify-between gap-2">
                                <span className="flex items-center gap-2">
                                  {indexBadge && (
                                    <span className="inline-flex h-5 min-w-5 items-center justify-center rounded-full bg-slate-800 text-[10px] font-bold text-slate-300 px-1">
                                      {indexBadge}
                                    </span>
                                  )}
                                  {label}
                                  {field.required !== false && <span className="text-amber-300"> *</span>}
                                </span>
                                <button type="button" className="text-xs font-semibold text-cyan-200 underline" onClick={() => activateField(field)}>
                                  {completed ? 'Edit' : 'Adopt'}
                                </button>
                              </label>
                              <input
                                type="text"
                                ref={(el) => {
                                  fieldInputRefs.current[field.id] = el;
                                }}
                                disabled={interactionLocked}
                                value={typeof fieldValues[field.id] === 'string' ? String(fieldValues[field.id]) : ''}
                                onChange={(e) => {
                                  const next = e.target.value.toUpperCase().replace(/[^A-Z]/g, '').slice(0, 4);
                                  setFieldValues((prev) => ({ ...prev, [field.id]: next }));
                                }}
                                placeholder="AB"
                                className="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2.5 text-sm text-white placeholder:text-slate-600"
                              />
                              {assistText && <div className="text-xs text-slate-400">{assistText}</div>}
                            </div>
                          );
                        }

                        return (
                          <div key={key} className={`space-y-1 rounded-lg border px-3 py-2.5 ${isActive ? 'border-cyan-400/60 bg-cyan-500/10' : 'border-white/10 bg-white/5'}`}>
                            <label className="text-sm text-slate-300 flex items-center justify-between gap-2">
                              <span className="flex items-center gap-2">
                                {indexBadge && (
                                  <span className="inline-flex h-5 min-w-5 items-center justify-center rounded-full bg-slate-800 text-[10px] font-bold text-slate-300 px-1">
                                    {indexBadge}
                                  </span>
                                )}
                                {label}
                                {field.required !== false && <span className="text-amber-300"> *</span>}
                              </span>
                              <button type="button" className="text-xs font-semibold text-cyan-200 underline" onClick={() => focusField(field)}>Jump</button>
                            </label>
                            <input
                              type={field.type === 'date' ? 'date' : 'text'}
                              ref={(el) => {
                                fieldInputRefs.current[field.id] = el;
                              }}
                              disabled={interactionLocked}
                              value={typeof fieldValues[field.id] === 'string' ? String(fieldValues[field.id]) : ''}
                              onChange={(e) => setFieldValues((prev) => ({ ...prev, [field.id]: e.target.value }))}
                              placeholder={field.placeholder || 'Enter value'}
                              className="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2.5 text-sm text-white placeholder:text-slate-600"
                            />
                            {assistText && <div className="text-xs text-slate-400">{assistText}</div>}
                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}

                <div className="space-y-2">
                  <label className="block text-[11px] font-bold text-slate-400 uppercase tracking-[0.22em]">Type your full legal name</label>
                  <input
                    ref={nameInputRef}
                    disabled={interactionLocked}
                    className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white placeholder:text-slate-600 focus:outline-none focus:ring-2 focus:ring-blue-500/50 transition"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    placeholder="e.g. John Doe"
                  />
                </div>

                {formError && (
                  <div className="rounded-xl border border-rose-500/40 bg-rose-500/10 px-3 py-2 text-xs text-rose-100">
                    {formError}
                  </div>
                )}

                <div className="space-y-2">
                  <Button
                    type="button"
                    disabled={!canCompleteNow}
                    onClick={handleQuickComplete}
                    className="w-full py-3.5 text-base font-bold shadow-lg shadow-blue-500/20"
                  >
                    {submitting ? 'Finalizing Signature…' : 'Complete Signature'}
                  </Button>
                  <Button
                    type="button"
                    variant="outline"
                    disabled={!canCompleteNow}
                    onClick={handleSubmit}
                    className="w-full"
                  >
                    Review Signature Style
                  </Button>
                </div>
              </div>
            </div>
          )}
        </div>
      </Card>

      {isCompactMobile && (
        <div className="fixed inset-x-0 bottom-0 z-[80] border-t border-white/10 bg-slate-950/95 backdrop-blur-xl">
          <div className="mx-auto w-full max-w-[1500px] px-3 py-2">
            <div className="rounded-2xl border border-white/10 bg-white/5 p-2">
              <div className="mb-2 text-[11px] text-slate-300">
                {interactionLocked
                  ? 'Unlock signing by acknowledging the e-sign disclosure first.'
                  : missingRequiredTabSteps.length > 0
                    ? `${missingRequiredTabSteps.length} required tab${missingRequiredTabSteps.length > 1 ? 's' : ''} left before submit.`
                    : 'All required tabs complete. You can finalize signature now.'}
              </div>
              <div className={`grid gap-2 ${hasSuggestedDefaults ? 'grid-cols-2' : 'grid-cols-1'}`}>
                {hasSuggestedDefaults && (
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    disabled={interactionLocked || submitting}
                    onClick={() => applySmartFieldAutofill(false)}
                    className="h-11 text-sm"
                  >
                    {autofillActionLabel}
                  </Button>
                )}
                <Button
                  type="button"
                  size="sm"
                  disabled={
                    interactionLocked ||
                    submitting ||
                    (missingRequiredTabSteps.length === 0 ? !canCompleteNow : false)
                  }
                  onClick={missingRequiredTabSteps.length > 0 ? goToNextMissingField : handleQuickComplete}
                  className="h-11 text-sm font-bold"
                >
                  {mobilePrimaryLabel}
                </Button>
              </div>
            </div>
          </div>
        </div>
      )}

      {showPdfFullscreen && (
        <div className="fixed inset-0 z-[9998] bg-slate-950/95 p-3 md:p-4">
          <div className="h-full w-full rounded-2xl border border-white/10 bg-slate-900/80 backdrop-blur-xl overflow-hidden">
            <div className="flex items-center justify-between gap-3 px-4 py-3 border-b border-white/10">
              <div>
                <h2 className="text-sm font-bold text-white">Contract packet — Full Screen</h2>
                <p className="text-xs text-slate-400">Use PDF zoom controls to inspect every sign/initial marker.</p>
              </div>
              <div className="flex items-center gap-2">
                {packetPdfPath && (
                  <a
                    href={packetPdfDownloadPath || packetPdfPath}
                    target="_blank"
                    rel="noreferrer"
                    className="text-xs font-semibold text-blue-200 underline"
                  >
                    Download PDF
                  </a>
                )}
                <Button type="button" variant="secondary" size="sm" onClick={() => setShowPdfFullscreen(false)}>
                  Close
                </Button>
              </div>
            </div>

            {packetPdfPath && (
              <div className="h-[calc(100vh-120px)] bg-slate-950/30">
                <InteractivePacketViewer
                  pdfUrl={packetPdfPath}
                  envelopeType={data?.envelopeType}
                  signerRole={signerRole}
                  fields={assignedFields}
                  activeFieldId={activeRequiredFieldId}
                  activeHotspotKey={activeRequiredTabKey}
                  missingFieldIds={missingRequiredFields.map((field) => field.id)}
                  missingHotspotKeys={missingRequiredTabKeys}
                  completedFieldIds={completedAssignedFieldIds}
                  completedHotspotKeys={completedRequiredTabKeys}
                  disabled={interactionLocked}
                  onActivateField={(fieldId, hotspotKey) => {
                    const targetField = assignedFields.find((field) => field.id === fieldId);
                    if (!targetField) return;
                    const targetStep = requiredTabSteps.find((step) => step.key === hotspotKey);
                    if (targetStep) {
                      activateTabStep(targetStep);
                    } else {
                      activateField(targetField);
                    }
                    setShowPdfFullscreen(false);
                  }}
                />
              </div>
            )}
          </div>
        </div>
      )}

      <StunningModal
        isOpen={showAdoptModal}
        onClose={closeAdoptModal}
        title={adoptModalTitle}
        subtitle={adoptModalSubtitle}
        size="lg"
        footer={
          <div className="flex gap-3">
            <ModalCancelButton onClick={closeAdoptModal}>Back</ModalCancelButton>
            <ModalPrimaryButton onClick={handleConfirmAdoptAndSign} disabled={!name || !initials || submitting} loading={submitting}>
              {adoptModalPrimaryLabel}
            </ModalPrimaryButton>
          </div>
        }
      >
        <div className="ae-sign-adopt-modal space-y-5">
          <ModalInput
            label="Full legal name"
            required
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="Enter your full legal name"
          />

          <ModalInput
            label="Initials"
            required
            value={initials}
            onChange={(e) => setInitials(e.target.value.toUpperCase().replace(/[^A-Z]/g, '').slice(0, 4))}
            placeholder="e.g. BP"
            maxLength={4}
          />

          <div>
            <div className="mb-2 text-sm font-semibold text-slate-700 dark:text-slate-200">Signature style</div>
            <div className="grid gap-2 sm:grid-cols-3">
              {[
                {
                  key: 'script',
                  label: 'Script',
                  previewClass: 'font-serif italic text-lg tracking-[0.01em]',
                  detail: 'Handwritten look',
                },
                {
                  key: 'classic',
                  label: 'Classic',
                  previewClass: 'font-semibold text-base tracking-[0.02em]',
                  detail: 'Formal and traditional',
                },
                {
                  key: 'clean',
                  label: 'Clean',
                  previewClass: 'font-mono text-base tracking-[0.04em]',
                  detail: 'Modern block style',
                },
              ].map((option) => (
                <button
                  key={option.key}
                  type="button"
                  onClick={() => setSignatureStyle(option.key as 'script' | 'classic' | 'clean')}
                  className={`rounded-xl border px-3 py-3 text-left transition ${
                    signatureStyle === option.key
                      ? 'border-blue-400 bg-blue-50 text-blue-900 shadow-[0_12px_28px_-16px_rgba(59,130,246,0.45)] dark:border-cyan-400 dark:bg-cyan-500/20 dark:text-cyan-100 dark:shadow-[0_12px_32px_rgba(34,211,238,0.14)]'
                      : 'border-slate-200 bg-white text-slate-700 hover:bg-slate-50 hover:border-slate-300 dark:border-white/10 dark:bg-white/5 dark:text-slate-300 dark:hover:bg-white/10 dark:hover:border-white/20'
                  }`}
                >
                  <div className="text-[10px] font-bold uppercase tracking-[0.22em] text-slate-500 dark:text-slate-400">
                    {option.label}
                  </div>
                  <div className={`mt-2 truncate text-slate-900 dark:text-white ${option.previewClass}`}>
                    {name || 'Your Signature'}
                  </div>
                  <div className="mt-1 text-[11px] text-slate-500 dark:text-slate-400">{option.detail}</div>
                </button>
              ))}
            </div>
          </div>

          <div className="rounded-2xl border border-slate-200/80 bg-[linear-gradient(135deg,rgba(248,250,252,0.98),rgba(239,246,255,0.92))] p-4 shadow-[0_18px_40px_-16px_rgba(15,23,42,0.22)] dark:border-white/10 dark:bg-[linear-gradient(135deg,rgba(15,23,42,0.92),rgba(8,47,73,0.85))] dark:shadow-[0_24px_60px_rgba(2,6,23,0.35)]">
            <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
              <div>
                <div className="text-[10px] font-bold uppercase tracking-wide text-slate-500 dark:text-slate-400">Preview</div>
                <div className="mt-2 text-xs text-slate-600 dark:text-slate-400">
                  {adoptModalMode === 'initials'
                    ? 'These initials will apply anywhere this packet needs your initials.'
                    : adoptModalMode === 'signature'
                      ? 'This adopted signature will be placed on your signature tab, with initials ready for the rest of the packet.'
                      : 'Review your adopted signature one last time before submitting the packet.'}
                </div>
              </div>
                <div className="inline-flex items-center rounded-full border border-blue-300/70 bg-blue-50 px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.18em] text-blue-700 dark:border-cyan-400/25 dark:bg-cyan-500/10 dark:text-cyan-100">
                {signerRoleLabel}
              </div>
            </div>

              <div className="mt-4 rounded-2xl border border-slate-200/80 bg-white p-4 shadow-[inset_0_1px_0_rgba(255,255,255,0.8)] dark:border-white/10 dark:bg-slate-950/70 dark:shadow-none">
                <div className="text-[10px] font-bold uppercase tracking-wide text-slate-500 dark:text-slate-500">Adopted signature</div>
                <div className={`mt-2 text-slate-900 dark:text-white ${signatureStyle === 'script' ? 'font-serif italic text-xl' : signatureStyle === 'classic' ? 'font-semibold text-lg' : 'font-mono text-lg tracking-[0.06em]'}`}>
                {name || 'Your Signature'}
              </div>
              <div className="mt-4 flex flex-wrap items-center gap-3">
                  <div className="inline-flex rounded-md border border-blue-300/60 bg-blue-50 px-2.5 py-1.5 text-xs font-bold text-blue-700 dark:border-cyan-400/40 dark:bg-cyan-500/10 dark:text-cyan-100">
                  {initials || 'INITIALS'}
                </div>
                  <div className="text-xs text-slate-600 dark:text-slate-400">
                  Ready for {requiredTabSteps.length} assigned tab{requiredTabSteps.length === 1 ? '' : 's'}
                </div>
              </div>
            </div>
          </div>
        </div>
      </StunningModal>

      {showDisclosurePrompt && !hash && !error && (
        <div
          data-testid="esign-disclosure-overlay"
          className="fixed inset-0 z-[9999] flex items-start justify-center overflow-y-auto overscroll-contain px-3 py-3 sm:items-center sm:p-4"
        >
          <div className="absolute inset-0 bg-slate-950/85 backdrop-blur-md" />
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(34,211,238,0.16),transparent_42%),radial-gradient(circle_at_bottom_right,rgba(59,130,246,0.18),transparent_35%)]" />

          <div
            data-testid="esign-disclosure-modal"
            className="relative z-10 flex max-h-[calc(100svh-1.5rem)] w-full max-w-2xl flex-col overflow-hidden rounded-2xl border border-white/12 bg-slate-950/95 shadow-2xl shadow-slate-950/60 sm:max-h-[calc(100vh-2rem)] sm:rounded-[28px]"
          >
            <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-cyan-400/60 to-transparent" />

            <div className="shrink-0 border-b border-white/5 px-4 pt-4 pb-3 sm:px-6 sm:pt-6 sm:pb-5">
              <div className="flex items-start gap-3 sm:gap-4">
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl border border-cyan-400/20 bg-cyan-500/15 text-cyan-200 sm:h-12 sm:w-12">
                  <svg className="h-5 w-5 sm:h-6 sm:w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M12 8v4m0 4h.01M4.93 19h14.14c1.54 0 2.5-1.67 1.73-3L13.73 3c-.77-1.33-2.69-1.33-3.46 0L3.2 16c-.77 1.33.19 3 1.73 3z" />
                  </svg>
                </div>
                <div className="min-w-0 flex-1">
                  <div className="text-[11px] font-bold uppercase tracking-[0.24em] text-cyan-200">Required before signing</div>
                  <h2 className="mt-1 text-xl font-bold leading-tight text-white sm:text-2xl">Review the e-sign disclosure</h2>
                  <p className="mt-2 max-w-xl text-xs leading-5 text-slate-300 sm:text-sm sm:leading-6">
                    This step is required before any packet tabs, fields, or signing actions unlock. It keeps the signing flow clear, compliant, and deliberate for every client, without requiring an app download or separate signing account.
                  </p>
                </div>
              </div>
            </div>

            <div className="min-h-0 flex-1 space-y-4 overflow-y-auto px-4 py-4 sm:space-y-5 sm:px-6 sm:py-5">
              <div className="flex flex-wrap gap-2">
                {disclosureSummary.map((item) => (
                  <div
                    key={item.label}
                    className="min-w-0 flex-1 basis-[9.5rem] rounded-2xl border border-white/10 bg-white/5 px-3 py-2 sm:min-w-[11rem] sm:rounded-full sm:px-4 sm:py-2.5"
                  >
                    <div className="text-[10px] font-bold uppercase tracking-[0.22em] text-slate-500">{item.label}</div>
                    <div className="mt-1 truncate text-sm font-semibold text-white">{item.value}</div>
                    <div className="mt-0.5 truncate text-xs text-slate-400">{item.detail}</div>
                  </div>
                ))}
              </div>

              <div className="flex flex-wrap gap-2">
                {disclosureHighlights.map((item) => (
                  <div
                    key={item}
                    className="rounded-full border border-cyan-400/20 bg-cyan-500/10 px-3 py-1.5 text-[11px] font-semibold tracking-[0.08em] text-cyan-100"
                  >
                    {item}
                  </div>
                ))}
              </div>

              <div className="rounded-2xl border border-white/10 bg-white/5 p-4">
                <div className="text-[11px] font-bold uppercase tracking-[0.22em] text-slate-500">How Signing Works</div>
                <div className="mt-3 grid gap-2 sm:gap-3 md:grid-cols-3">
                  {disclosureSteps.map((item) => (
                    <div key={item.step} className="rounded-xl border border-white/8 bg-slate-950/50 px-3 py-2.5 sm:py-3">
                      <div className="inline-flex h-6 w-6 items-center justify-center rounded-full border border-cyan-400/30 bg-cyan-500/10 text-[11px] font-bold text-cyan-100">
                        {item.step}
                      </div>
                      <div className="mt-2 text-sm font-semibold text-white sm:mt-3">{item.title}</div>
                      <div className="mt-1 text-xs leading-5 text-slate-300 sm:text-sm sm:leading-6">{item.detail}</div>
                    </div>
                  ))}
                </div>
              </div>

              <div className={`rounded-2xl border px-4 py-4 ${rulesAcknowledged ? 'border-emerald-500/35 bg-emerald-500/10' : 'border-amber-500/35 bg-amber-500/10'}`}>
                <label className="flex items-start gap-3 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={rulesAcknowledged}
                    onChange={(e) => setRulesAcknowledged(e.target.checked)}
                    className="mt-0.5 rounded border-slate-600 bg-slate-800 text-emerald-500 focus:ring-2 focus:ring-emerald-500"
                  />
                  <span className="text-sm text-slate-200">
                    <span className="font-semibold text-white">E-sign disclosure acknowledgement:</span> I consent to electronic records and signatures, understand this is legally binding, and confirm I am authorized to sign for this role.
                  </span>
                </label>
              </div>
            </div>

            <div className="shrink-0 border-t border-white/5 bg-slate-950/60 px-4 py-4 sm:px-6 sm:py-5">
              <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                <div className="text-xs text-slate-400">
                  {rulesAcknowledged
                    ? 'Disclosure accepted. Start with your first required tab and finish at your own pace.'
                    : 'Acknowledge the disclosure to unlock your signer tabs and continue.'}
                </div>
                <div className="flex gap-3 sm:w-auto w-full">
                  {rulesAcknowledged && (
                    <Button type="button" variant="outline" onClick={() => setShowDisclosurePrompt(false)} className="sm:w-auto w-full">
                      Back to Packet
                    </Button>
                  )}
                  <Button type="button" onClick={closeDisclosurePrompt} disabled={!rulesAcknowledged} className="sm:w-auto w-full">
                    {disclosurePrimaryLabel}
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
