-- Ensure AgentProfileSettings exists and has all columns (safe for existing DBs)
CREATE TABLE IF NOT EXISTS "AgentProfileSettings" (
  "id" TEXT NOT NULL,
  "agentId" TEXT NOT NULL,
  "firstName" TEXT,
  "lastName" TEXT,
  "phone" TEXT,
  "licenseNumber" TEXT,
  "licenseState" TEXT,
  "licenseExpiry" TIMESTAMP(3),
  "timezone" TEXT NOT NULL DEFAULT 'America/Denver',
  "signatureBlock" TEXT,
  "photoUrl" TEXT,
  "yearsExperience" INTEGER,
  "specializations" TEXT,
  "bio" TEXT,
  "brokerageName" TEXT,
  "brokerageLogoUrl" TEXT,
  "brokerageAddress" TEXT,
  "brokeragePhone" TEXT,
  "officeAddress" TEXT,
  "brokerageLicense" TEXT,
  "brandColor" TEXT NOT NULL DEFAULT '#3B82F6',
  "accentColor" TEXT NOT NULL DEFAULT '#06B6D4',
  "logoUrl" TEXT,
  "websiteUrl" TEXT,
  "googleAnalyticsId" TEXT,
  "facebookUrl" TEXT,
  "instagramUrl" TEXT,
  "linkedinUrl" TEXT,
  "emailFooter" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "AgentProfileSettings_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "AgentProfileSettings_agentId_key" ON "AgentProfileSettings" ("agentId");

ALTER TABLE "AgentProfileSettings"
  ADD COLUMN IF NOT EXISTS "licenseState" TEXT,
  ADD COLUMN IF NOT EXISTS "licenseExpiry" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "timezone" TEXT NOT NULL DEFAULT 'America/Denver',
  ADD COLUMN IF NOT EXISTS "signatureBlock" TEXT,
  ADD COLUMN IF NOT EXISTS "photoUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "yearsExperience" INTEGER,
  ADD COLUMN IF NOT EXISTS "specializations" TEXT,
  ADD COLUMN IF NOT EXISTS "bio" TEXT,
  ADD COLUMN IF NOT EXISTS "brokerageName" TEXT,
  ADD COLUMN IF NOT EXISTS "brokerageLogoUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "brokerageAddress" TEXT,
  ADD COLUMN IF NOT EXISTS "brokeragePhone" TEXT,
  ADD COLUMN IF NOT EXISTS "officeAddress" TEXT,
  ADD COLUMN IF NOT EXISTS "brokerageLicense" TEXT,
  ADD COLUMN IF NOT EXISTS "brandColor" TEXT NOT NULL DEFAULT '#3B82F6',
  ADD COLUMN IF NOT EXISTS "accentColor" TEXT NOT NULL DEFAULT '#06B6D4',
  ADD COLUMN IF NOT EXISTS "logoUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "websiteUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "googleAnalyticsId" TEXT,
  ADD COLUMN IF NOT EXISTS "facebookUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "instagramUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "linkedinUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "emailFooter" TEXT;
