-- AlterEnum
-- Add new values to ListingStatus enum
ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'ACTIVE_NO_SHOW';
ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'BACKUP';
ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'WITHDRAWN';
ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'CANCELED';
ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';
